# Default values for workshop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
db:
  replicaCount: 1
  name: db
  internalPort: 55555
  externalPort: 55555
  image: microsoft/mssql-server-linux
  pullPolicy: IfNotPresent
  eula: ACCEPT_EULA
  eulaValue: Y
  tag: latest
  pullPolicy: IfNotPresent
  eula: ACCEPT_EULA
  eulaValue: \Y
  sa: SA_PASSWORD
  saValue: ConferencePlanner1234$
  restart: Always

frontend:
  replicaCount: 1
  name: frontend
  internalPort: 80
  externalPort: 80
  image: frontend
  tag: latest
  environment: Production
  pullPolicy: IfNotPresent
  restart: Always

backend:
  replicaCount: 1
  name: backend
  internalPort: 80
  externalPort: 80
  image: backend
  tag: latest
  environment: Production
  pullPolicy: IfNotPresent
  restart: Always

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
