apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" .}}-lb
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    service: {{ .Values.frontend.name }}
    release: {{ .Release.Name }}